# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Jun 23 12:48:15 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1062, 650)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lblPath = QtGui.QLabel(self.centralwidget)
        self.lblPath.setGeometry(QtCore.QRect(0, 580, 1062, 21))
        self.lblPath.setFrameShape(QtGui.QFrame.Panel)
        self.lblPath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblPath.setText(_fromUtf8(""))
        self.lblPath.setObjectName(_fromUtf8("lblPath"))
        self.btnUpdate = QtGui.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(420, 470, 85, 27))
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 702, 161))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(122, 155, 216)"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 40, 581, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KacstOne"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(270, 100, 301, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.lblMoto = QtGui.QLabel(self.splitter)
        self.lblMoto.setStyleSheet(_fromUtf8("background-color: white"))
        self.lblMoto.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblMoto.setFrameShadow(QtGui.QFrame.Raised)
        self.lblMoto.setObjectName(_fromUtf8("lblMoto"))
        self.lnCountMoto = QtGui.QLineEdit(self.splitter)
        self.lnCountMoto.setStyleSheet(_fromUtf8("background-color: rgb(250, 250, 250)"))
        self.lnCountMoto.setObjectName(_fromUtf8("lnCountMoto"))
        self.lblQuad = QtGui.QLabel(self.splitter)
        self.lblQuad.setStyleSheet(_fromUtf8("background-color: white"))
        self.lblQuad.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblQuad.setFrameShadow(QtGui.QFrame.Raised)
        self.lblQuad.setObjectName(_fromUtf8("lblQuad"))
        self.lnCountQuad = QtGui.QLineEdit(self.splitter)
        self.lnCountQuad.setStyleSheet(_fromUtf8("background-color: rgb(250, 250, 250)"))
        self.lnCountQuad.setObjectName(_fromUtf8("lnCountQuad"))
        self.lblAuto = QtGui.QLabel(self.splitter)
        self.lblAuto.setStyleSheet(_fromUtf8("background-color: white"))
        self.lblAuto.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblAuto.setFrameShadow(QtGui.QFrame.Raised)
        self.lblAuto.setObjectName(_fromUtf8("lblAuto"))
        self.lnCountCar = QtGui.QLineEdit(self.splitter)
        self.lnCountCar.setStyleSheet(_fromUtf8("background-color: rgb(250, 250, 250)"))
        self.lnCountCar.setObjectName(_fromUtf8("lnCountCar"))
        self.tblGralStatus = QtGui.QTableWidget(self.centralwidget)
        self.tblGralStatus.setGeometry(QtCore.QRect(10, 190, 702, 271))
        self.tblGralStatus.setMinimumSize(QtCore.QSize(120, 271))
        self.tblGralStatus.setStyleSheet(_fromUtf8("font: 9pt \"Noto Sans Thai UI\";"))
        self.tblGralStatus.setObjectName(_fromUtf8("tblGralStatus"))
        self.tblGralStatus.setColumnCount(11)
        self.tblGralStatus.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tblGralStatus.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tblGralStatus.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tblGralStatus.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tblGralStatus.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tblGralStatus.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tblGralStatus.setHorizontalHeaderItem(10, item)
        self.tblData = QtGui.QTableWidget(self.centralwidget)
        self.tblData.setGeometry(QtCore.QRect(730, 10, 202, 177))
        self.tblData.setObjectName(_fromUtf8("tblData"))
        self.tblData.setColumnCount(1)
        self.tblData.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tblData.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblData.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblData.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblData.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblData.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblData.setHorizontalHeaderItem(0, item)
        self.lblUpdate = QtGui.QLabel(self.centralwidget)
        self.lblUpdate.setGeometry(QtCore.QRect(10, 480, 371, 17))
        self.lblUpdate.setText(_fromUtf8(""))
        self.lblUpdate.setObjectName(_fromUtf8("lblUpdate"))
        self.btnNewFile = QtGui.QPushButton(self.centralwidget)
        self.btnNewFile.setGeometry(QtCore.QRect(550, 470, 85, 27))
        self.btnNewFile.setObjectName(_fromUtf8("btnNewFile"))
        self.pgFile = QtGui.QProgressBar(self.centralwidget)
        self.pgFile.setGeometry(QtCore.QRect(710, 490, 118, 23))
        self.pgFile.setProperty("value", 0)
        self.pgFile.setObjectName(_fromUtf8("pgFile"))
        self.tblWpt = QtGui.QTableWidget(self.centralwidget)
        self.tblWpt.setGeometry(QtCore.QRect(730, 220, 151, 121))
        self.tblWpt.setObjectName(_fromUtf8("tblWpt"))
        self.tblWpt.setColumnCount(2)
        self.tblWpt.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblWpt.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblWpt.setHorizontalHeaderItem(1, item)
        self.tblDz = QtGui.QTableWidget(self.centralwidget)
        self.tblDz.setGeometry(QtCore.QRect(730, 350, 151, 121))
        self.tblDz.setObjectName(_fromUtf8("tblDz"))
        self.tblDz.setColumnCount(2)
        self.tblDz.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblDz.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblDz.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOpen = QtGui.QMenu(self.menuFile)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        self.menuParametres = QtGui.QMenu(self.menubar)
        self.menuParametres.setObjectName(_fromUtf8("menuParametres"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionFolder = QtGui.QAction(MainWindow)
        self.actionFolder.setObjectName(_fromUtf8("actionFolder"))
        self.actionDirectoryPath = QtGui.QAction(MainWindow)
        self.actionDirectoryPath.setObjectName(_fromUtf8("actionDirectoryPath"))
        self.actionCategory = QtGui.QAction(MainWindow)
        self.actionCategory.setObjectName(_fromUtf8("actionCategory"))
        self.actionEditZone = QtGui.QAction(MainWindow)
        self.actionEditZone.setObjectName(_fromUtf8("actionEditZone"))
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionFolder)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addSeparator()
        self.menuParametres.addAction(self.actionDirectoryPath)
        self.menuParametres.addAction(self.actionCategory)
        self.menuParametres.addAction(self.actionEditZone)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuParametres.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dakar 2015", None))
        self.btnUpdate.setText(_translate("MainWindow", "Update", None))
        self.label.setText(_translate("MainWindow", "DESAFIO RUTA 40 - 2015                     ETAPA    1", None))
        self.lblMoto.setText(_translate("MainWindow", "Motos", None))
        self.lblQuad.setText(_translate("MainWindow", "Quad", None))
        self.lblAuto.setText(_translate("MainWindow", "Autos", None))
        item = self.tblGralStatus.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Competidor N°", None))
        item = self.tblGralStatus.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.tblGralStatus.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "N° Orden", None))
        item = self.tblGralStatus.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Categoría", None))
        item = self.tblGralStatus.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "WPT", None))
        item = self.tblGralStatus.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DZ", None))
        item = self.tblGralStatus.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Disc", None))
        item = self.tblGralStatus.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cod", None))
        item = self.tblGralStatus.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Version", None))
        item = self.tblGralStatus.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "GPS N°", None))
        item = self.tblGralStatus.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Observaciones", None))
        item = self.tblData.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Competidor N°:", None))
        item = self.tblData.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "GPS N°:", None))
        item = self.tblData.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nombre:", None))
        item = self.tblData.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fecha:", None))
        item = self.tblData.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Hora:", None))
        self.btnNewFile.setText(_translate("MainWindow", "New Files", None))
        item = self.tblWpt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WPT", None))
        item = self.tblDz.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DZ", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuOpen.setTitle(_translate("MainWindow", "Open", None))
        self.menuParametres.setTitle(_translate("MainWindow", "Parametres", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionFile.setText(_translate("MainWindow", "File", None))
        self.actionFolder.setText(_translate("MainWindow", "Folder", None))
        self.actionDirectoryPath.setText(_translate("MainWindow", "Directory Path", None))
        self.actionCategory.setText(_translate("MainWindow", "Category", None))
        self.actionEditZone.setText(_translate("MainWindow", "Edit Zone", None))

